SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

CREATE SCHEMA IF NOT EXISTS `vhoj` ;
USE `vhoj`;

-- -----------------------------------------------------
-- Table `vhoj`.`T_USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vhoj`.`T_USER` ;

CREATE  TABLE IF NOT EXISTS `vhoj`.`T_USER` (
  `C_ID` INT(10) NOT NULL AUTO_INCREMENT ,
  `C_USERNAME` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL ,
  `C_NICKNAME` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL ,
  `C_PASSWORD` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL ,
  `C_CREATETIME` DATETIME NULL DEFAULT NULL ,
  `C_QQ` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL ,
  `C_SCHOOL` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL ,
  `C_EMAIL` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL ,
  `C_BLOG` VARCHAR(1000) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL ,
  `C_SHARE` INT(10) UNSIGNED NOT NULL DEFAULT '1' ,
  `C_SUP` INT(10) UNSIGNED NOT NULL DEFAULT '0' ,
  PRIMARY KEY (`C_ID`) )
ENGINE = InnoDB
AUTO_INCREMENT = 1000
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `vhoj`.`T_CONTEST`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vhoj`.`T_CONTEST` ;

CREATE  TABLE IF NOT EXISTS `vhoj`.`T_CONTEST` (
  `C_ID` INT(10) NOT NULL AUTO_INCREMENT ,
  `C_TITLE` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL ,
  `C_DESCRIPTION` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL ,
  `C_PASSWORD` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL ,
  `C_BEGINTIME` DATETIME NULL DEFAULT NULL ,
  `C_ENDTIME` DATETIME NULL DEFAULT NULL ,
  `C_MANAGERID` INT(10) NULL DEFAULT NULL ,
  PRIMARY KEY (`C_ID`) ,
  INDEX `C_MANAGERID` (`C_MANAGERID` ASC) ,
  CONSTRAINT `C_MANAGERID`
    FOREIGN KEY (`C_MANAGERID` )
    REFERENCES `vhoj`.`T_USER` (`C_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1000
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `vhoj`.`T_PROBLEM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vhoj`.`T_PROBLEM` ;

CREATE  TABLE IF NOT EXISTS `vhoj`.`T_PROBLEM` (
  `C_ID` INT(10) NOT NULL AUTO_INCREMENT ,
  `C_TITLE` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL ,
  `C_DESCRIPTION` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL ,
  `C_INPUT` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL ,
  `C_OUTPUT` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL ,
  `C_SAMPLEINPUT` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL ,
  `C_SAMPLEOUTPUT` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL ,
  `C_HINT` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL ,
  `C_SOURCE` VARCHAR(500) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL ,
  `C_URL` VARCHAR(500) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL ,
  `C_originOJ` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL ,
  `C_originProb` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL ,
  `C_addTime` DATETIME NULL DEFAULT NULL ,
  `C_MEMORYLIMIT` INT(10) NULL DEFAULT NULL ,
  `C_TIMELIMIT` INT(10) UNSIGNED NULL DEFAULT NULL ,
  `C_CREATORID` INT(10) UNSIGNED NULL DEFAULT NULL ,
  `C_HIDDEN` INT(10) UNSIGNED NULL DEFAULT NULL ,
  PRIMARY KEY (`C_ID`) )
ENGINE = InnoDB
AUTO_INCREMENT = 1000
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `vhoj`.`T_CPROBLEM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vhoj`.`T_CPROBLEM` ;

CREATE  TABLE IF NOT EXISTS `vhoj`.`T_CPROBLEM` (
  `C_ID` INT(10) NOT NULL AUTO_INCREMENT ,
  `C_PROBLEMID` INT(10) NULL DEFAULT NULL ,
  `C_CONTESTID` INT(10) NULL DEFAULT NULL ,
  `C_NUM` VARCHAR(2) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL ,
  PRIMARY KEY (`C_ID`) ,
  INDEX `C_PROBLEMID` (`C_PROBLEMID` ASC) ,
  INDEX `C_CONTESTID` (`C_CONTESTID` ASC) ,
  CONSTRAINT `C_CONTESTID`
    FOREIGN KEY (`C_CONTESTID` )
    REFERENCES `vhoj`.`T_CONTEST` (`C_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `C_PROBLEMID`
    FOREIGN KEY (`C_PROBLEMID` )
    REFERENCES `vhoj`.`T_PROBLEM` (`C_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1000
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `vhoj`.`T_SUBMISSION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vhoj`.`T_SUBMISSION` ;

CREATE  TABLE IF NOT EXISTS `vhoj`.`T_SUBMISSION` (
  `C_ID` INT(10) NOT NULL AUTO_INCREMENT ,
  `C_STATUS` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL ,
  `C_TIME` INT(10) UNSIGNED NULL DEFAULT NULL ,
  `C_MEMORY` INT(10) UNSIGNED NULL DEFAULT NULL ,
  `C_SUBTIME` DATETIME NULL DEFAULT NULL ,
  `C_PROBLEMID` INT(10) NULL DEFAULT NULL ,
  `C_USERID` INT(10) NULL DEFAULT NULL ,
  `C_CONTESTID` INT(10) NULL DEFAULT NULL ,
  `C_LANGUAGE` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL ,
  `C_SOURCE` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL ,
  `C_ISOPEN` INT(10) NULL DEFAULT NULL ,
  PRIMARY KEY (`C_ID`) ,
  INDEX `C_PROBLEMID2` (`C_PROBLEMID` ASC) ,
  INDEX `C_USERID` (`C_USERID` ASC) ,
  INDEX `C_CPROBLEMID` USING BTREE (`C_CONTESTID` ASC) ,
  CONSTRAINT `C_PROBLEMID2`
    FOREIGN KEY (`C_PROBLEMID` )
    REFERENCES `vhoj`.`T_PROBLEM` (`C_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `C_USERID`
    FOREIGN KEY (`C_USERID` )
    REFERENCES `vhoj`.`T_USER` (`C_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1000
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
