CREATE TABLE `vhoj`.`t_replay_status` (
  `C_ID` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  `C_DATA` MEDIUMTEXT COLLATE utf8_unicode_ci,
  PRIMARY KEY (`C_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

ALTER TABLE `vhoj`.`t_contest` ADD COLUMN `C_REPLAY_STATUS_ID` INT(10) UNSIGNED AFTER `C_HASH_CODE`,
 ADD INDEX `Index_replay_status_id`(`C_REPLAY_STATUS_ID`);
